# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0.xci
# IP: The module: 'Final_Optional_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Optional_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Optional_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Optional_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0.xci
# IP: The module: 'Final_Optional_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Optional_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Optional_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ibai/ESDC/Final_Optional/Final_Optional.srcs/sources_1/bd/Final_Optional/ip/Final_Optional_axi_gpio_0_0/Final_Optional_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Final_Optional_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
